version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: usgs_earthquakes

models:
  - name: earthquakes
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: magnitude
        tests:
          - not_null
      - name: origin_time
        tests:
          - not_null